sidebar:
  menu:
    post: "[btn.blog](/)"
    wiki: "[btn.wiki](/wiki/)"
    # notes: "[笔记](/notes/)"
    more: "[关于](/about/)"
  widgets:
    #### 自动生成的页面 ####
    # 主页
    home: search, welcome,recent,tagcloud, timeline # for home
    # 博客索引页
    blog_index: search_blog,welcome, recent, timeline # for categories/tags/archives
    # 文档索引页
    wiki_index: search_docs, recent, timeline # for wiki
    # 其它（404）
    others: search, welcome, recent, timeline # for 404 and ...
    #### 手动创建的页面 ####
    # 文章内页
    post: search,toc, ghrepo, ghissues # for pages using 'layout:post'
    # 文档内页
    wiki: search, ghrepo, toc, # for pages using 'layout:wiki'
    # 其它 layout:page 的页面
    page: search,toc # for custom pages using 'layout:page'

# 文章搜索
search:
  service: local_search # local_search, todo...
  local_search: # 在 front-matter 中设置 indexing:false 来避免被搜索索引
    field: all # post, page, all
    path: /search.json # 搜索文件存放位置
    content: true # 是否搜索内容
    codeblock: true # 是否搜索代码块（需要content: true)

style:
  font-size:
    root: 18px
    body: 1.0375rem # 15px
    code: 85% # 14px
    codeblock: 0.8125rem # 13px
  font-family:
    body: fangzheng_yuan,'system-ui, "Microsoft Yahei", "Segoe UI", -apple-system, Roboto, Ubuntu, "Helvetica Neue", Arial, "WenQuanYi Micro Hei", sans-serif'
  # codeblock:
  #   highlightjs_theme: /custom/css/ZYCode.css
  darkmode: false # auto / always / false

article:
  auto_cover: true
  auto_excerpt: 100

footer:
  social:
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/25678f144c438.svg"/>'
      url: /atom.xml
    - icon: '<img src="https://cdn.jsdelivr.net/gh/cdn-x/placeholder@1.0.1/social/08a41b181ce68.svg"/>'
      url: https://github.com/mikaelzero
  sitemap:
    "博客":
      - "[近期](/)"
      - "[标签](/tags)"
      - "[归档](/archives)"
    "项目":
      - "[开源库](/wiki)"
    "更多":
      - "[关于本站](/about)"
      - "[GitHub](https://github.com/mikaelzero)"
  content: |
    本站由 [@mikaelzero](/) 使用 [Stellar](https://github.com/xaoxuu/hexo-theme-stellar) 主题创建。
    本博客所有文章除特别声明外，均采用 [CC BY-NC-SA 4.0](https://creativecommons.org/licenses/by-nc-sa/4.0/) 许可协议，转载请注明出处。

loading:
  loading: 正在加载
  error: 加载失败，请稍后重试。
