# 相关配置说明
  # favicon: 网站图标
  # avatar: 主题用户头像与昵称
  # rss: rss订阅
  # prevnext: 文章末尾的上一页与下一页
  # footer: 页脚信息
  # search: 文章搜索

# enable: 是否开启相应功能，可选true || false

# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: ARTICLE
  path: /

# 文章末尾的上一页与下一页
prevnext:
  enable: true

# 链接信息
link: 


# 页脚信息
footer:

# 文章搜索
search:
  enable: false
  placeholder: 
